/**
 * Rejstřík ověřených citací stránky rolí (arch_iter-030_T-001 sekce 15,
 * ověřeno skriptem proti PDF 29. 9. 2026). Vygenerováno z tabulky návrhu,
 * citace doslovně včetně apostrofů z PDF. Klíč = id z rejstříku (G1, M20 …).
 * U manuálu je strana PDF = vytištěné číslo (M01: 2. strana PDF, tištěno „ii").
 */
import type { SourceRef } from "@/lib/info-pages/types";

export const ROLE_SOURCES: Record<string, SourceRef> = {
  G1: { doc: "general-policies", page: 1, rule: "General Policies, úvod", quoteEn: "Membership Committees of each chapter have final authority related to BNI Policies." },
  G2: { doc: "general-policies", page: 1, rule: "General Policies, úvod", quoteEn: "Membership Committees may put a BNI Member on probation or open a Member’s classification for failure to comply with the Member Policies, the Code of Ethics or BNI Core Values." },
  G3: { doc: "general-policies", page: 1, rule: "General Policy #8", quoteEn: "Only BNI Members who have completed the Member Success Program, and BNI Directors/Director Consultants can do Feature Presentations during the BNI Meetings." },
  G4: { doc: "general-policies", page: 1, rule: "General Policy #9", quoteEn: "Leaves of absence are possible for certain extenuating circumstances (e.g., extended medical issue that prevents members from working) at the discretion of the Membership Committee." },
  G5: { doc: "general-policies", page: 1, rule: "General Policy #10", quoteEn: "Members who wish to change their BNI classification must submit a new membership application for approval." },
  G6: { doc: "general-policies", page: 1, rule: "General Policy #11", quoteEn: "Before sending any marketing or business solicitation communications to BNI Members outside your chapter or Director/Director Consultants, the recipient must give their consent." },
  G7: { doc: "general-policies", page: 1, rule: "General Policies, závěr", quoteEn: "All proposed policy changes need to be reviewed first by the International Board of Advisors" },
  G8: { doc: "general-policies", page: 2, rule: "Administrative Policy #1", quoteEn: "Contact the local Secretary/Treasurer for amounts and payment instructions." },
  G9: { doc: "general-policies", page: 2, rule: "Administrative Policy #2", quoteEn: "BNI reserves the right to open more than one Chapter per community or city where demand of BNI’s services are requested." },
  G10: { doc: "general-policies", page: 2, rule: "Administrative Policy #3", quoteEn: "If fees are not paid within 15 days, the Member will be officially dropped by BNI." },
  G11: { doc: "general-policies", page: 2, rule: "Administrative Policy #4", quoteEn: "Fees cannot be transferred from one person to another unless the fees are from the same company." },
  G12: { doc: "general-policies", page: 2, rule: "Administrative Policy #5", quoteEn: "A Certificate of Credit will be given, upon request, to Members in good standing for the unused portion of their time." },
  G13: { doc: "general-policies", page: 2, rule: "Administrative Policy #6", quoteEn: "A Member has three working days in which to contact their Regional BNI office and resolve the matter." },
  G14: { doc: "general-policies", page: 2, rule: "Administrative Policy #7", quoteEn: "BNI or any of its franchisees reserve the right to discontinue a Member’s participation in this program." },
  G15: { doc: "general-policies", page: 3, rule: "Administrative Policy #8", quoteEn: "will be required to submit a completed new Member application to the Membership Committee of the new Chapter." },
  G16: { doc: "general-policies", page: 3, rule: "Program Guidelines", quoteEn: "Program Guidelines are not policies but recommended practices that allow Chapters to run more smoothly and effectively." },
  G17: { doc: "general-policies", page: 3, rule: "Absences and Tardiness", quoteEn: "the Membership Committee may give warnings to Members who are consistently late or leave early." },
  G18: { doc: "general-policies", page: 4, rule: "Business Representation #1", quoteEn: "Members agree to only represent the professional classification approved by the Membership Committee." },
  M01: { doc: "ops-manual-2022", page: 2, quoteEn: "references made to a Director may refer to a Director, Director Consultant, Area Director, Sr. Director Consultant, Regional Director Franchisee (Executive Director) or Master Franchisee (National Director)." },
  M02: { doc: "ops-manual-2022", page: 9, rule: "Non-Discrimination", quoteEn: "BNI will support no Chapter’s action when in violation of this non-discrimination statement." },
  M03: { doc: "ops-manual-2022", page: 9, rule: "No Harassment", quoteEn: "BNI does not tolerate harassment of our Franchisees, regional teams, leadership teams or Members at the hand of another." },
  M05: { doc: "ops-manual-2022", page: 11, quoteEn: "no agenda has proven more effective than the BNI Weekly Meeting Agenda." },
  M07: { doc: "ops-manual-2022", page: 27, quoteEn: "Chapters with 50+ Members may collectively agree to facilitate the BNI Weekly Meeting Agenda beyond 90 minutes with Executive Director/Regional Director approval." },
  M08: { doc: "ops-manual-2022", page: 28, quoteEn: "Ultimately, it is the Visitor Host and follow up efforts from the Regional Team that support overcoming objections and converting visitors into Members." },
  M09: { doc: "ops-manual-2022", page: 31, quoteEn: "You may choose to align it with the Director Consultant visits to the Chapter." },
  M11: { doc: "ops-manual-2022", page: 32, quoteEn: "At this point the President, Secretary/Treasurer and Visitors Host leave the meeting." },
  M12: { doc: "ops-manual-2022", page: 32, quoteEn: "The Vice President facilitates the remainder of the meeting." },
  M13: { doc: "ops-manual-2022", page: 32, quoteEn: "If not, the Leadership Team Members with open roles should fill those roles within the next month." },
  M14: { doc: "ops-manual-2022", page: 33, quoteEn: "Only the Vice President, Membership Committee and Director Consultant (if present) are in attendance for the remainder." },
  M15: { doc: "ops-manual-2022", page: 33, quoteEn: "The final decision on non-renewal should happen on or around the Member’s renewal date." },
  M16: { doc: "ops-manual-2022", page: 33, quoteEn: "It is important that the BNI Regional Office knows the person is not going to be renewed" },
  M17: { doc: "ops-manual-2022", page: 34, quoteEn: "Mentor Coordinator (Not MC)" },
  M18: { doc: "ops-manual-2022", page: 35, quoteEn: "The President facilitates a smooth, timely meeting by following the BNI Weekly Meeting Agenda" },
  M19: { doc: "ops-manual-2022", page: 35, quoteEn: "ensures all leaders are fulfilling their responsibilities; provides direction and motivation for the Chapter to meet its goals; communicates weekly with the Director Consultant." },
  M20: { doc: "ops-manual-2022", page: 35, quoteEn: "After Membership Committee approval, call to welcome accepted applicants to the Chapter" },
  M21: { doc: "ops-manual-2022", page: 35, quoteEn: "To be on the Leadership Team, the President agrees to:" },
  M22: { doc: "ops-manual-2022", page: 36, quoteEn: "Participate in the Weekly Chapter Success Call with your Director (along with your Vice President and Secretary/Treasurer)" },
  M23: { doc: "ops-manual-2022", page: 36, quoteEn: "Participate in the Leadership Team Selection Process as guided by your Director." },
  M24: { doc: "ops-manual-2022", page: 36, quoteEn: "Facilitate the first half of the Chapter Success Meeting. If present, your Director Consultant may attend" },
  M25: { doc: "ops-manual-2022", page: 36, quoteEn: "Select one meeting theme to use during one Chapter meeting per month" },
  M26: { doc: "ops-manual-2022", page: 37, quoteEn: "All venue changes are subject to the approval of the Regional or Area Director PRIOR to making a change." },
  M27: { doc: "ops-manual-2022", page: 37, quoteEn: "The Chapter Leadership Team chooses a theme for one week, once a month or less." },
  M28: { doc: "ops-manual-2022", page: 39, quoteEn: "The Vice President is the manager of the Membership Committee" },
  M29: { doc: "ops-manual-2022", page: 39, quoteEn: "enforces the attendance policy by monitoring the automated attendance emails and assigning Membership Committee Members to make follow-up phone calls" },
  M30: { doc: "ops-manual-2022", page: 39, quoteEn: "Meeting Agenda if President is absent" },
  M31: { doc: "ops-manual-2022", page: 40, quoteEn: "Assign a completion date and conference call to discuss and vote" },
  M32: { doc: "ops-manual-2022", page: 41, quoteEn: "Each Chapter must establish a Membership Committee." },
  M33: { doc: "ops-manual-2022", page: 41, quoteEn: "There should always be an odd number of members on this committee, including the Vice President." },
  M34: { doc: "ops-manual-2022", page: 41, quoteEn: "The Membership Committee is a volunteer service commitment that coincides with the Leadership Team’s term." },
  M35: { doc: "ops-manual-2022", page: 41, quoteEn: "The Membership Committee is led by the Vice President, who is an equal voting member of the committee." },
  M36: { doc: "ops-manual-2022", page: 41, quoteEn: "the Vice Present of each Chapter is still responsible for making sure each task is completed in a timely manner." },
  M37: { doc: "ops-manual-2022", page: 41, quoteEn: "Assign one Membership Committee to each of these four roles" },
  M38: { doc: "ops-manual-2022", page: 41, quoteEn: "Delegate a Membership Committee Member to deliver the report, and the Vice President approves the report in advance" },
  M39: { doc: "ops-manual-2022", page: 41, quoteEn: "Explain the roles of the Membership Committee and who is responsible for each." },
  M40: { doc: "ops-manual-2022", page: 41, quoteEn: "Meetings are open only to the Vice President, Membership Committee members and the Director/Director Consultant" },
  M41: { doc: "ops-manual-2022", page: 42, quoteEn: "ensures all new Members are high-quality business professionals and have a strategic fit (BNI Classification) within the Chapter before they are accepted into the Chapter." },
  M42: { doc: "ops-manual-2022", page: 42, quoteEn: "Submit signed BNI Support Leadership Team Non-Disclosure, Non-Solicitation and Non-Compete Agreement" },
  M45: { doc: "ops-manual-2022", page: 47, quoteEn: "The Membership Committee will let you know the status of your application before the next meeting." },
  M46: { doc: "ops-manual-2022", page: 51, quoteEn: "This list is not meant to be either exhaustive or binding." },
  M47: { doc: "ops-manual-2022", page: 51, quoteEn: "There is an unacceptable overlap in BNI Classification between a prospective Member and a current Member (as determined by the Membership Committee)." },
  M48: { doc: "ops-manual-2022", page: 51, quoteEn: "If a Member of another Chapter approaches your Chapter about transferring, please contact your Director/Director Consultant so that he/she can walk you through the process." },
  M49: { doc: "ops-manual-2022", page: 52, quoteEn: "ensures all renewals are approved/declined in a timely manner." },
  M50: { doc: "ops-manual-2022", page: 53, quoteEn: "Decide if the Member should be declined upon the next renewal" },
  M51: { doc: "ops-manual-2022", page: 54, quoteEn: "Get approval from Vice President and Director/Director Consultant prior to sending the Open Classification Letter and making the fourth absence phone call" },
  M52: { doc: "ops-manual-2022", page: 55, quoteEn: "Always notify your BNI Director/Director Consultant when it becomes necessary to open a Member’s classification." },
  M53: { doc: "ops-manual-2022", page: 56, quoteEn: "a credit will be issued by the local BNI Director/Director Consultant." },
  M54: { doc: "ops-manual-2022", page: 56, quoteEn: "Please note that a credit will never be issued to facilitate a transfer to a nearby Chapter." },
  M55: { doc: "ops-manual-2022", page: 56, quoteEn: "A Member may take a medical leave of absence with the Membership Committee’s prior approval if their participation fees are pre-paid for the period of time" },
  M56: { doc: "ops-manual-2022", page: 56, quoteEn: "although longer leave may be granted at the discretion of the Membership Committee." },
  M57: { doc: "ops-manual-2022", page: 57, quoteEn: "When you receive a request for a request for medical leave, please contact your Director/Director Consultant to walk you through the process." },
  M58: { doc: "ops-manual-2022", page: 57, quoteEn: "Receives incoming concerns and complaints, verbal and written" },
  M59: { doc: "ops-manual-2022", page: 57, quoteEn: "Contacts Vice President and Director/Director Consultant as soon as a written complaint is submitted" },
  M60: { doc: "ops-manual-2022", page: 58, quoteEn: "Member submits complaint in writing to the Membership Committee. This must happen before the Membership Committee proceeds to the next step." },
  M61: { doc: "ops-manual-2022", page: 58, quoteEn: "Vice President contacts the Director/Director Consultant for support PRIOR to proceeding." },
  M62: { doc: "ops-manual-2022", page: 58, quoteEn: "The Membership Committee may, however, open a Member’s classification without probation, if warranted, with Director/Director Consultant and Executive Director/Regional Director approval." },
  M63: { doc: "ops-manual-2022", page: 58, quoteEn: "Decision is made by majority vote of a complete and fully trained Membership Committee." },
  M64: { doc: "ops-manual-2022", page: 58, quoteEn: "Full Membership Committee, including the Vice President, meets to discuss the interviews" },
  M65: { doc: "ops-manual-2022", page: 59, quoteEn: "Only a majority vote is needed from the Membership Committee (including the Vice President) to pursue probation; however, attempt to seek consensus." },
  M66: { doc: "ops-manual-2022", page: 59, quoteEn: "Confirmation from the Director/Director Consultant that the process was followed is required." },
  M67: { doc: "ops-manual-2022", page: 59, quoteEn: "Length of probation time is determined by the Membership Committee." },
  M68: { doc: "ops-manual-2022", page: 59, quoteEn: "Always involve and get approval from your Director/Director Consultant that the process was followed PRIOR to opening a Member’s classification." },
  M69: { doc: "ops-manual-2022", page: 59, quoteEn: "they may open the Member’s classification to a more qualified reliable professional, with Director/Director Consultant and Executive Director approval." },
  M70: { doc: "ops-manual-2022", page: 59, quoteEn: "If the concern at hand is a Chapter-wide topic, ask the Director/Director Consultant to conduct a Feature Presentation to address the issue." },
  M71: { doc: "ops-manual-2022", page: 59, quoteEn: "In the event a dispute arises involving a Membership Committee member, the Member will be removed from their duties during the dispute processing" },
  M72: { doc: "ops-manual-2022", page: 60, quoteEn: "The Vice President may call on other Members as deemed necessary." },
  M73: { doc: "ops-manual-2022", page: 60, quoteEn: "Once complete, submit a copy to the BNI Regional Office." },
  M74: { doc: "ops-manual-2022", page: 60, quoteEn: "Have Director/Director Consultant approve prior to distributing letter." },
  M75: { doc: "ops-manual-2022", page: 60, quoteEn: "Always sign the letters from “The Membership Committee”; never use an individual name." },
  M76: { doc: "ops-manual-2022", page: 60, quoteEn: "In all cases, these letters should be emailed to your Director/Director Consultant and the BNI Regional Office at the time it is sent to the applicant/Member." },
  M77: { doc: "ops-manual-2022", page: 62, quoteEn: "The Secretary/Treasurer tracks, announces and collects new and renewal application and participation fees" },
  M78: { doc: "ops-manual-2022", page: 63, quoteEn: "Pay bills with the approval of the President" },
  M79: { doc: "ops-manual-2022", page: 63, quoteEn: "Create a budget for your BNI Chapter" },
  M80: { doc: "ops-manual-2022", page: 63, quoteEn: "Participate in the Leadership Team Selection Process as guided by your Director/Director Consultant." },
  M81: { doc: "ops-manual-2022", page: 64, quoteEn: "Be sure to include your Director/Director Consultant’s speaking schedule, if provided to you in advance." },
  M82: { doc: "ops-manual-2022", page: 64, quoteEn: "are not coordinated by a Director/Director Consultant and are solely at the discretion of the individual Members." },
  M83: { doc: "ops-manual-2022", page: 64, quoteEn: "this is at the sole discretion of the Members of the Chapter, and they take sole responsibility for the operation of the bank account." },
  M84: { doc: "ops-manual-2022", page: 65, quoteEn: "Neither BNI Global LLC nor the BNI Franchisee will be liable for non-BNI–related activity bank accounts." },
  M85: { doc: "ops-manual-2022", page: 65, quoteEn: "All BNI participation fees are to be sent to the BNI Regional Office to process." },
  M86: { doc: "ops-manual-2022", page: 65, quoteEn: "BNI does not authorize Chapters to process participation fees through these or any other accounts." },
  M87: { doc: "ops-manual-2022", page: 65, quoteEn: "Remember, Secretary/Treasurers do not deposit membership and application payments; these are sent to the BNI Regional Office for further processing." },
  M88: { doc: "ops-manual-2022", page: 65, quoteEn: "Two signatures to sign cheques are strongly recommended, typically the President and Secretary/Treasurer." },
  M89: { doc: "ops-manual-2022", page: 65, quoteEn: "Whenever one of the signatories is no longer responsible for the account, a replacement should be selected by the Members." },
  M90: { doc: "ops-manual-2022", page: 66, quoteEn: "Visitor Hosts make a positive first impression on the visitors and substitutes of the Chapter" },
  M91: { doc: "ops-manual-2022", page: 67, quoteEn: "Please alert your Chapter Director so they assist with their BNI interest." },
  M92: { doc: "ops-manual-2022", page: 67, quoteEn: "Attend Monthly Leadership Team Meetings on behalf of the Visitor Host Team" },
  M93: { doc: "ops-manual-2022", page: 72, quoteEn: "The Education Coordinator prepares a two to three-minute Networking Education Moment" },
  M94: { doc: "ops-manual-2022", page: 72, quoteEn: "Communicate with Chapter President weekly to ensure the upcoming Networking Education Moments are in line with Chapter goals" },
  M95: { doc: "ops-manual-2022", page: 72, quoteEn: "May assign Members to provide the Networking Education Moment each week" },
  M96: { doc: "ops-manual-2022", page: 75, quoteEn: "The Mentor Coordinator makes sure each new Chapter Member completes the Mentor Program" },
  M97: { doc: "ops-manual-2022", page: 78, quoteEn: "Once the Mentor Coordinator and the Membership Committee have identified Member Mentor candidates it is important for them to be trained." },
  M98: { doc: "ops-manual-2022", page: 78, quoteEn: "Avoid assigning one person to multiple roles." },
  M99: { doc: "ops-manual-2022", page: 80, quoteEn: "The Vice President is the overall manager of the renewal process" },
  M100: { doc: "ops-manual-2022", page: 80, quoteEn: "If Membership Committee decides not to renew the Member and the VP denies the renewal in BNI Connect, the emails to the member stop." },
  M101: { doc: "ops-manual-2022", page: 80, quoteEn: "If no action occurs by VP by 14 days prior to renewal date, the Member is automatically approved." },
  M102: { doc: "ops-manual-2022", page: 80, quoteEn: "VP and Director are sent alert emails" },
  // T-010r3: doplněno mimo rejstřík návrhu, doslova z textu manuálu str. 35
  // (orchestration/runs/iter-029/zdroje/BNI_Chapter_Operations_Manual_2022-2023.txt).
  M104: { doc: "ops-manual-2022", page: 35, quoteEn: "facilitates monthly Leadership Team Meetings" },
  M103: { doc: "ops-manual-2022", page: 30, quoteEn: "Ensuring there is cooperation amongst all Members in the Chapter through the selection of BNI Classifications is a key responsibility of the Quality Assurance Membership Committee Member." },
};
